Add errors UI
alwaysbegrowing/events pull request #9
Opened 2022-09-02 16:36 UTC by Bookcliff

2022-09-05 22:07 UTC, RusseII reviewed
Nice changes! Seems to function well. Is it possible to simplify the loading state? Here's an example of how they handle the loading state in the docs: https://swr.vercel.app/docs/getting-started#make-it-reusable

2022-09-08 12:23 UTC, Bookcliff commented
> Nice changes! Seems to function well. Is it possible to simplify the loading state? Here's an example of how they handle the loading state in the docs: https://swr.vercel.app/docs/getting-started#make-it-reusable

Added!

2022-09-08 12:42 UTC, RusseII requested changes

2022-09-08 12:42 UTC, RusseII commented on src/App.js
> +function GetData(contractAddress) {
this is a hook, so should be called `useData` 
<img width="778" alt="CleanShot 2022-09-08 at 07 40 23@2x" src="https://user-images.githubusercontent.com/15036618/189124111-275ab792-3f13-4872-a386-b436c4695ed7.png">

https://reactjs.org/docs/hooks-overview.html#building-your-own-hooks

2022-09-08 12:42 UTC, RusseII commented on src/App.js
> +          (contractEvents.abi === "Invalid Address format") |
this is OK for now but you could simplify this by just throwing an error in the fetcher and you could remove the extra state variable https://swr.vercel.app/docs/error-handling

2022-09-08 22:13 UTC, Bookcliff commented on src/App.js
> +function GetData(contractAddress) {
Done

2022-09-12 12:01 UTC, Bookcliff commented on src/App.js
> +          (contractEvents.abi === "Invalid Address format") |
Done

2022-09-12 12:46 UTC, RusseII approved these changes

2022-09-13 12:44 UTC, merged